# Generated by Django 5.1.6 on 2026-09-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Бот включён')),
                ('auto_like', models.BooleanField(default=True, verbose_name='Ставить лайк автоматически')),
                ('auto_send', models.BooleanField(default=True, verbose_name='Отправлять текст автоматически')),
                ('use_vision', models.BooleanField(default=False, verbose_name='Отдавать фото в модель (vision)')),
                ('tone', models.CharField(choices=[('warm', 'Тёплый и лёгкий'), ('romantic', 'Романтично-красивый'), ('playful', 'Игривый с юмором')], default='romantic', max_length=16, verbose_name='Тон')),
                ('max_chars', models.PositiveIntegerField(default=320, verbose_name='Максимум символов в сообщении')),
                ('extra_instructions', models.TextField(blank=True, default='', verbose_name='Доп. инструкции для модели')),
                ('daily_limit', models.PositiveIntegerField(default=40, verbose_name='Лимит сообщений в сутки')),
                ('min_delay', models.FloatField(default=4.0, verbose_name='Мин. пауза перед действием, сек')),
                ('max_delay', models.FloatField(default=14.0, verbose_name='Макс. пауза перед действием, сек')),
                ('paused_until', models.DateTimeField(blank=True, null=True, verbose_name='Пауза до')),
                ('min_age', models.PositiveSmallIntegerField(default=18, verbose_name='Мин. возраст анкеты')),
                ('max_age', models.PositiveSmallIntegerField(default=99, verbose_name='Макс. возраст анкеты')),
                ('city_filter', models.CharField(blank=True, default='', max_length=128, verbose_name='Фильтр по городу (подстрока, пусто = любой)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки бота',
                'verbose_name_plural': 'Настройки бота',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, verbose_name='ID чата')),
                ('message_id', models.BigIntegerField(default=0, verbose_name='ID сообщения')),
                ('grouped_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID альбома')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('city', models.CharField(blank=True, default='', max_length=128, verbose_name='Город')),
                ('about', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('raw_caption', models.TextField(blank=True, default='', verbose_name='Исходная подпись')),
                ('language', models.CharField(blank=True, default='', max_length=8, verbose_name='Язык анкеты')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Локальные пути к фото')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='Отпечаток (для дедупликации)')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('generated', 'Текст сгенерирован'), ('sent', 'Отправлено'), ('skipped', 'Пропущена'), ('failed', 'Ошибка')], db_index=True, default='new', max_length=16, verbose_name='Статус')),
                ('skip_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина пропуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('language', models.CharField(blank=True, default='', max_length=8, verbose_name='Язык ответа')),
                ('strategy', models.CharField(blank=True, default='', max_length=32, verbose_name='Сценарий')),
                ('model', models.CharField(blank=True, default='', max_length=64, verbose_name='Модель')),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='matcher.profile', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Сгенерированное сообщение',
                'verbose_name_plural': 'Сгенерированные сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(db_index=True, default='info', max_length=8)),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='matcher.profile')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Журнал событий',
                'ordering': ['-created_at'],
            },
        ),
    ]
