# Generated by Django 5.1.6 on 2026-09-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='language',
            field=models.CharField(choices=[('auto', 'Как в анкете'), ('ru', 'Всегда русский'), ('uz', 'Всегда узбекский'), ('en', 'Всегда английский')], default='auto', max_length=8, verbose_name='Язык ответа'),
        ),
    ]
